# Generated by Django 6.0.6 on 2026-07-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
