# Generated by Django 6.0.6 on 2026-07-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_recipient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
