# Generated by Django 6.0.6 on 2026-07-04 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_bank_code'),
        ('payroll', '0002_salarybatch_total_records_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarybatch',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='salarybatch',
            name='total_records',
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='reference',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payroll.salarybatch'),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_transactions', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
